[package]
name = "ledgerstats"
version = "0.1.0"
edition = "2021"
authors = ["Valerii Reutov"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.74"
clap = "2.27.1"
itertools = "0.11.0"
thiserror = "1.0.24"
